const turkeyProvinces = [
    "Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Amasya", "Ankara", "Antalya", "Artvin", "Aydın", "Balıkesir",
    "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli",
    "Diyarbakır", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkari",
    "Hatay", "Isparta", "Mersin", "İstanbul", "İzmir", "Kars", "Kastamonu", "Kayseri", "Kırklareli", "Kırşehir",
    "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Kahramanmaraş", "Mardin", "Muğla", "Muş", "Nevşehir",
    "Niğde", "Ordu", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Tekirdağ", "Tokat",
    "Trabzon", "Tunceli", "Şanlıurfa", "Uşak", "Van", "Yozgat", "Zonguldak", "Aksaray", "Bayburt", "Karaman",
    "Kırıkkale", "Batman", "Şırnak", "Bartın", "Ardahan", "Iğdır", "Yalova", "Karabük", "Kilis", "Osmaniye", "Düzce"
];

const turkeyUniversitiesByProvince = {
    "Adana": ["Çukurova Üniversitesi", "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi", "Çağ Üniversitesi"],
    "Adıyaman": ["Adıyaman Üniversitesi"],
    "Afyonkarahisar": ["Afyon Kocatepe Üniversitesi", "Afyonkarahisar Sağlık Bilimleri Üniversitesi"],
    "Ağrı": ["Ağrı İbrahim Çeçen Üniversitesi"],
    "Amasya": ["Amasya Üniversitesi"],
    "Ankara": ["Ankara Üniversitesi", "Gazi Üniversitesi", "Orta Doğu Teknik Üniversitesi", "Hacettepe Üniversitesi", "İhsan Doğramacı Bilkent Üniversitesi", "Başkent Üniversitesi", "Ankara Hacı Bayram Veli Üniversitesi", "Ankara Medipol Üniversitesi", "Ankara Müzik ve Güzel Sanatlar Üniversitesi", "Ankara Sosyal Bilimler Üniversitesi", "Ankara Yıldırım Beyazıt Üniversitesi", "Atılım Üniversitesi", "Çankaya Üniversitesi", "Lokman Hekim Üniversitesi", "Ostim Teknik Üniversitesi", "TED Üniversitesi", "TOBB Ekonomi ve Teknoloji Üniversitesi", "Türk Hava Kurumu Üniversitesi", "Ufuk Üniversitesi", "Yüksek İhtisas Üniversitesi"],
    "Antalya": ["Akdeniz Üniversitesi", "Alanya Alaaddin Keykubat Üniversitesi", "Antalya Bilim Üniversitesi", "Alanya Üniversitesi"],
    "Artvin": ["Artvin Çoruh Üniversitesi"],
    "Aydın": ["Aydın Adnan Menderes Üniversitesi"],
    "Balıkesir": ["Balıkesir Üniversitesi", "Bandırma Onyedi Eylül Üniversitesi"],
    "Bilecik": ["Bilecik Şeyh Edebali Üniversitesi"],
    "Bingöl": ["Bingöl Üniversitesi"],
    "Bitlis": ["Bitlis Eren Üniversitesi"],
    "Bolu": ["Bolu Abant İzzet Baysal Üniversitesi"],
    "Burdur": ["Burdur Mehmet Akif Ersoy Üniversitesi"],
    "Bursa": ["Bursa Uludağ Üniversitesi", "Bursa Teknik Üniversitesi", "Mudanya Üniversitesi"],
    "Çanakkale": ["Çanakkale Onsekiz Mart Üniversitesi"],
    "Çankırı": ["Çankırı Karatekin Üniversitesi"],
    "Çorum": ["Hitit Üniversitesi"],
    "Denizli": ["Pamukkale Üniversitesi"],
    "Diyarbakır": ["Dicle Üniversitesi"],
    "Edirne": ["Trakya Üniversitesi"],
    "Elazığ": ["Fırat Üniversitesi"],
    "Erzincan": ["Erzincan Binali Yıldırım Üniversitesi"],
    "Erzurum": ["Atatürk Üniversitesi", "Erzurum Teknik Üniversitesi"],
    "Eskişehir": ["Anadolu Üniversitesi", "Eskişehir Osmangazi Üniversitesi", "Eskişehir Teknik Üniversitesi"],
    "Gaziantep": ["Gaziantep Üniversitesi", "Gaziantep İslam Bilim ve Teknoloji Üniversitesi", "Hasan Kalyoncu Üniversitesi", "Sanko Üniversitesi"],
    "Giresun": ["Giresun Üniversitesi"],
    "Gümüşhane": ["Gümüşhane Üniversitesi"],
    "Hakkari": ["Hakkari Üniversitesi"],
    "Hatay": ["Hatay Mustafa Kemal Üniversitesi", "İskenderun Teknik Üniversitesi"],
    "Isparta": ["Süleyman Demirel Üniversitesi", "Isparta Uygulamalı Bilimler Üniversitesi"],
    "Mersin": ["Mersin Üniversitesi", "Tarsus Üniversitesi", "Toros Üniversitesi"],
    "İstanbul": ["İstanbul Üniversitesi", "İstanbul Teknik Üniversitesi", "Boğaziçi Üniversitesi", "Marmara Üniversitesi", "Yıldız Teknik Üniversitesi", "Galatasaray Üniversitesi", "İstanbul Üniversitesi-Cerrahpaşa", "İstanbul Medeniyet Üniversitesi", "Türk-Alman Üniversitesi", "Acıbadem Üniversitesi", "Altınbaş Üniversitesi", "Bahçeşehir Üniversitesi", "Beykent Üniversitesi", "Beykoz Üniversitesi", "Bezmialem Vakıf Üniversitesi", "Biruni Üniversitesi", "Doğuş Üniversitesi", "Fatih Sultan Mehmet Vakıf Üniversitesi", "Fenerbahçe Üniversitesi", "Haliç Üniversitesi", "Işık Üniversitesi", "İbn Haldun Üniversitesi", "İstanbul 29 Mayıs Üniversitesi", "İstanbul Arel Üniversitesi", "İstanbul Atlas Üniversitesi", "İstanbul Aydın Üniversitesi", "İstanbul Bilgi Üniversitesi", "İstanbul Esenyurt Üniversitesi", "İstanbul Galata Üniversitesi", "İstanbul Gedik Üniversitesi", "İstanbul Gelişim Üniversitesi", "İstanbul Kent Üniversitesi", "İstanbul Kültür Üniversitesi", "İstanbul Medipol Üniversitesi", "İstanbul Okan Üniversitesi", "İstanbul Rumeli Üniversitesi", "İstanbul Sabahattin Zaim Üniversitesi", "İstanbul Sağlık ve Teknoloji Üniversitesi", "İstanbul Şişli Meslek Yüksekokulu", "İstanbul Ticaret Üniversitesi", "İstanbul Topkapı Üniversitesi", "İstinye Üniversitesi", "Kadir Has Üniversitesi", "Koç Üniversitesi", "Maltepe Üniversitesi", "MEF Üniversitesi", "Nişantaşı Üniversitesi", "Özyeğin Üniversitesi", "Piri Reis Üniversitesi", "Sabancı Üniversitesi", "Sağlık Bilimleri Üniversitesi", "Üsküdar Üniversitesi", "Yeditepe Üniversitesi", "Yeni Yüzyıl Üniversitesi"],
    "İzmir": ["Ege Üniversitesi", "Dokuz Eylül Üniversitesi", "İzmir Yüksek Teknoloji Enstitüsü", "İzmir Katip Çelebi Üniversitesi", "İzmir Bakırçay Üniversitesi", "İzmir Demokrasi Üniversitesi", "İzmir Ekonomi Üniversitesi", "İzmir Tınaztepe Üniversitesi", "Yaşar Üniversitesi"],
    "Kars": ["Kafkas Üniversitesi"],
    "Kastamonu": ["Kastamonu Üniversitesi"],
    "Kayseri": ["Erciyes Üniversitesi", "Kayseri Üniversitesi", "Nuh Naci Yazgan Üniversitesi", "Abdullah Gül Üniversitesi"],
    "Kırklareli": ["Kırklareli Üniversitesi"],
    "Kırşehir": ["Kırşehir Ahi Evran Üniversitesi"],
    "Kocaeli": ["Kocaeli Üniversitesi", "Gebze Teknik Üniversitesi", "Kocaeli Sağlık ve Teknoloji Üniversitesi"],
    "Konya": ["Selçuk Üniversitesi", "Necmettin Erbakan Üniversitesi", "Konya Teknik Üniversitesi", "KTO Karatay Üniversitesi", "Konya Gıda ve Tarım Üniversitesi"],
    "Kütahya": ["Kütahya Dumlupınar Üniversitesi", "Kütahya Sağlık Bilimleri Üniversitesi"],
    "Malatya": ["İnönü Üniversitesi", "Malatya Turgut Özal Üniversitesi"],
    "Manisa": ["Manisa Celal Bayar Üniversitesi"],
    "Kahramanmaraş": ["Kahramanmaraş Sütçü İmam Üniversitesi", "Kahramanmaraş İstiklal Üniversitesi"],
    "Mardin": ["Mardin Artuklu Üniversitesi"],
    "Muğla": ["Muğla Sıtkı Koçman Üniversitesi"],
    "Muş": ["Muş Alparslan Üniversitesi"],
    "Nevşehir": ["Nevşehir Hacı Bektaş Veli Üniversitesi"],
    "Niğde": ["Niğde Ömer Halisdemir Üniversitesi"],
    "Ordu": ["Ordu Üniversitesi"],
    "Rize": ["Recep Tayyip Erdoğan Üniversitesi"],
    "Sakarya": ["Sakarya Üniversitesi", "Sakarya Uygulamalı Bilimler Üniversitesi"],
    "Samsun": ["Ondokuz Mayıs Üniversitesi", "Samsun Üniversitesi"],
    "Siirt": ["Siirt Üniversitesi"],
    "Sinop": ["Sinop Üniversitesi"],
    "Sivas": ["Sivas Cumhuriyet Üniversitesi", "Sivas Bilim ve Teknoloji Üniversitesi"],
    "Tekirdağ": ["Tekirdağ Namık Kemal Üniversitesi"],
    "Tokat": ["Tokat Gaziosmanpaşa Üniversitesi"],
    "Trabzon": ["Karadeniz Teknik Üniversitesi", "Trabzon Üniversitesi", "Avrasya Üniversitesi"],
    "Tunceli": ["Munzur Üniversitesi"],
    "Şanlıurfa": ["Harran Üniversitesi"],
    "Uşak": ["Uşak Üniversitesi"],
    "Van": ["Van Yüzüncü Yıl Üniversitesi"],
    "Yozgat": ["Yozgat Bozok Üniversitesi"],
    "Zonguldak": ["Zonguldak Bülent Ecevit Üniversitesi"],
    "Aksaray": ["Aksaray Üniversitesi"],
    "Bayburt": ["Bayburt Üniversitesi"],
    "Karaman": ["Karamanoğlu Mehmetbey Üniversitesi"],
    "Kırıkkale": ["Kırıkkale Üniversitesi"],
    "Batman": ["Batman Üniversitesi"],
    "Şırnak": ["Şırnak Üniversitesi"],
    "Bartın": ["Bartın Üniversitesi"],
    "Ardahan": ["Ardahan Üniversitesi"],
    "Iğdır": ["Iğdır Üniversitesi"],
    "Yalova": ["Yalova Üniversitesi"],
    "Karabük": ["Karabük Üniversitesi"],
    "Kilis": ["Kilis 7 Aralık Üniversitesi"],
    "Osmaniye": ["Osmaniye Korkut Ata Üniversitesi"],
    "Düzce": ["Düzce Üniversitesi"]
};

// Geriye dönük uyumluluk için tüm üniversitelerin düz listesi (opsiyonel)
const turkeyUniversities = Object.values(turkeyUniversitiesByProvince).flat();

const turkeyHighSchools = [
    "Anadolu Lisesi",
    "Fen Lisesi",
    "Sosyal Bilimler Lisesi",
    "Mesleki ve Teknik Anadolu Lisesi",
    "Anadolu İmam Hatip Lisesi",
    "Çok Programlı Anadolu Lisesi",
    "Güzel Sanatlar Lisesi",
    "Spor Lisesi",
    "Açık Öğretim Lisesi",
    "Akşam Lisesi",
    "İlkokulu",
    "Ortaokulu"
];
